### ISSUE TITLE
Installation Steps

### ISSUE THREAD

**Issue by zaqoutabed** [mituldavid/drive#1]
What is the right way to **install / use**  Drive in production server ?

these steps that i follow to use Drive

1. get-app
2. install-app
3. go to /drive/frontend/ and run **yarn build**
4. I found there is files generated in **public/frontend/** folder

and in the server i try to access <host>/drive i get 404 error
![image](https://user-images.githubusercontent.com/26047413/159538454-b9acad26-475c-4fe4-aceb-50b054c3c34a.png)

could you help and create installation steps in production server plz.?

**Comment by mituldavid** [comment]
Hey, I have setup the production build configuration via commit 67cee816dd8446e197fadefbdd53ca45b3b8b73a. You should be able to run `yarn build` in the drive/frontend folder to build for production now.
